export const BRAND = "StartNow";

export const CATEGORY_META = {
  clutter: { icon: "🧹", label: "Orden" },
  distraction: { icon: "📵", label: "Distracciones" },
  overwhelm: { icon: "🧠", label: "Sobrecarga" },
  communication: { icon: "💬", label: "Conversaciones pendientes" },
  mindset: { icon: "🌱", label: "Autoexigencia" },
};

// Mapea las respuestas del quiz a la categoría que más se enfatiza en el mensaje de bienvenida.
export const TRIGGER_TO_CATEGORY = {
  "Estrés y ansiedad": "overwhelm",
  "Pensar demasiado": "overwhelm",
  "Perfeccionismo": "mindset",
  "Inseguridad": "mindset",
  "Problemas de pareja o familia": "communication",
  "Trauma emocional": "mindset",
};
export const AVOIDANCE_TO_CATEGORY = {
  overwhelm: "overwhelm",
  distraction: "distraction",
};

export const WEEKS = [
  { week: 1, title: "Victorias de 2 minutos", desc: "Tareas mínimas para que tu cerebro aprenda a terminar cosas." },
  { week: 2, title: "Cortar el ciclo de distracción", desc: "Bajar la fricción de las decisiones que más postergás." },
  { week: 3, title: "Consistencia sin fuerza de voluntad", desc: "Mantener lo logrado sin tener que esforzarte más." },
  { week: 4, title: "Patrones automáticos", desc: "Lo nuevo deja de sentirse como un esfuerzo." },
];

export const PLAN = [
  { day: 1, week: 1, category: "clutter", minutes: 2,
    title: "Tres objetos fuera de lugar",
    lesson: "No se trata de los objetos. Se trata de entrenar a tu cerebro para completar micro-compromisos sin pensarlo de más.",
    task: "Guarda tres objetos que tengas a la vista ahora mismo. Nada más." },
  { day: 2, week: 1, category: "distraction", minutes: 3,
    title: "Silencio selectivo",
    lesson: "Cada notificación reabre una decisión que tu cerebro ya había cerrado. Menos interrupciones, menos fatiga.",
    task: "Silencia las notificaciones de una sola aplicación durante las próximas 2 horas." },
  { day: 3, week: 1, category: "clutter", minutes: 5,
    title: "Vaciar, no ordenar",
    lesson: "Vaciar una superficie por completo, sin decidir dónde va cada cosa, evita la fatiga de decisión que te paraliza.",
    task: "Elige una sola superficie plana. Vacíala por completo. No la ordenes todavía — solo vacíala." },
  { day: 4, week: 1, category: "overwhelm", minutes: 4,
    title: "Nombrar la lista",
    lesson: "Nombrar lo que evitás, sin actuar todavía, le baja el volumen a la ansiedad que genera tenerlo \"flotando\".",
    task: "Escribe las 3 tareas pendientes que más evitás. No las hagas todavía — solo nómbralas." },
  { day: 5, week: 1, category: "communication", minutes: 3,
    title: "El mensaje que evitás",
    lesson: "Postergar una conversación la hace más grande en tu cabeza de lo que es en realidad.",
    task: "Envía un mensaje que llevás días postergando. Puede ser tan simple como \"Hola, ¿seguimos en pie?\"." },
  { day: 6, week: 1, category: "clutter", minutes: 5,
    title: "Cinco prendas",
    lesson: "Las victorias pequeñas y repetidas entrenan a tu cerebro mejor que un esfuerzo grande y aislado.",
    task: "Guarda 5 prendas de ropa que estén fuera de lugar." },
  { day: 7, week: 1, category: "overwhelm", minutes: 5, checkin: true,
    title: "Archivar tres cosas",
    lesson: "Fin de la primera semana. Revisa: ¿dejaste de preguntarte \"¿por dónde empiezo?\" tan seguido como antes?",
    task: "Archiva o elimina 3 documentos (físicos o digitales) que ya no necesitas en tu escritorio." },

  { day: 8, week: 2, category: "distraction", minutes: 5,
    title: "Bandeja de entrada",
    lesson: "Una bandeja saturada es una lista de decisiones sin tomar. Reducirla baja el ruido de fondo.",
    task: "Borra 20 correos viejos de tu bandeja de entrada." },
  { day: 9, week: 2, category: "mindset", minutes: 8,
    title: "El 80% también cuenta",
    lesson: "El perfeccionismo no te hace terminar mejor — te hace no terminar. Practicar el \"suficientemente bueno\" es una habilidad.",
    task: "Elige una tarea \"perfecta\" pendiente y hazla al 80%. Detente ahí a propósito." },
  { day: 10, week: 2, category: "distraction", minutes: 2,
    title: "Fricción a propósito",
    lesson: "No necesitás fuerza de voluntad si le agregás un paso extra al hábito que querés reducir.",
    task: "Mueve el ícono de tu red social favorita a la última pantalla del celular." },
  { day: 11, week: 2, category: "overwhelm", minutes: 5,
    title: "Dividir en tres",
    lesson: "Las tareas grandes generan un enredo de opciones compitiendo entre sí. Dividirlas te devuelve una sola vía clara.",
    task: "Divide tu tarea más grande pendiente en 3 pasos chicos. Escríbelos." },
  { day: 12, week: 2, category: "clutter", minutes: 4,
    title: "Decidir o borrar",
    lesson: "Las decisiones pendientes ocupan espacio mental aunque no las estés mirando.",
    task: "Revisa una lista o carrito de compras pendiente: decide comprarlo o bórralo." },
  { day: 13, week: 2, category: "communication", minutes: 3,
    title: "Agendar, no resolver",
    lesson: "Agendar una conversación difícil es un compromiso pequeño que le quita el peso de \"algún día\".",
    task: "Agenda (todavía no la tengas, solo agéndala) esa conversación difícil que venís evitando." },
  { day: 14, week: 2, category: "distraction", minutes: 25, checkin: true,
    title: "Bloque protegido",
    lesson: "Fin de la semana 2. Un bloque sin interrupciones entrena a tu cerebro a tolerar el impulso de revisar el celular.",
    task: "Activa \"No molestar\" durante tu próximo bloque de trabajo de 25 minutos." },

  { day: 15, week: 3, category: "clutter", minutes: 5,
    title: "Listo para mañana",
    lesson: "Empezar el día con un espacio despejado reduce las decisiones que tenés que tomar antes de las 9am.",
    task: "Antes de acostarte, deja tu escritorio o tu cocina listos para mañana." },
  { day: 16, week: 3, category: "overwhelm", minutes: 10,
    title: "Lo urgente primero",
    lesson: "Revisar el celular antes de empezar reinicia el enredo de opciones que tanto cuesta ordenar.",
    task: "Elige la tarea más urgente del día y hazla primero, antes de revisar el celular." },
  { day: 17, week: 3, category: "mindset", minutes: 3,
    title: "Y aun así seguí",
    lesson: "Ser duro/a con vos mismo/a después de un error no te hace más productivo/a — solo te cansa más rápido.",
    task: "Anota un error reciente y complétalo con la frase: \"y aun así seguí adelante\"." },
  { day: 18, week: 3, category: "distraction", minutes: 8,
    title: "Menos de 15",
    lesson: "Mantener la bandeja baja es más fácil que vaciarla de una vez — por eso funciona como hábito diario.",
    task: "Revisa tu bandeja de entrada y déjala en menos de 15 correos sin archivar." },
  { day: 19, week: 3, category: "communication", minutes: 10,
    title: "La conversación agendada",
    lesson: "El paso más difícil ya lo diste el día 13. Hoy solo hace falta sostenerlo.",
    task: "Ten esa conversación que agendaste el día 13, o reagéndala con una fecha concreta." },
  { day: 20, week: 3, category: "clutter", minutes: 10,
    title: "La prueba de la alegría",
    lesson: "Tocar cada objeto y preguntarte si te genera alegría te obliga a decidir de verdad, en vez de posponer la decisión otra vez. No se trata de tener menos cosas — se trata de otra relación con esas cosas.",
    task: "Elegí una categoría chica (tus medias, tus remeras, tus libros). Tomá cada objeto en la mano y preguntate: ¿esto me genera alegría? Si la respuesta es no, agradecele y donalo o descartalo." },
  { day: 21, week: 3, category: "overwhelm", minutes: 5, checkin: true,
    title: "La tarea sin vueltas",
    lesson: "Fin de la semana 3. El objetivo no es la perfección — es notar el cambio en cómo empezás las cosas.",
    task: "Revisa tu semana: ¿qué tarea completaste sin darle mil vueltas? Anótala." },

  { day: 22, week: 4, category: "mindset", minutes: 2,
    title: "Reconocerlo en voz alta",
    lesson: "Nombrar tus propios avances refuerza el circuito tanto como completar la tarea en sí.",
    task: "Nota una tarea que hiciste hoy sin procrastinar. Reconócelo en voz alta." },
  { day: 23, week: 4, category: "clutter", minutes: 10,
    title: "Ese cajón",
    lesson: "Ya tenés el hábito instalado — este tipo de tarea que antes te tomaba una tarde ahora te toma minutos.",
    task: "Organiza un cajón o una carpeta digital que te moleste hace tiempo." },
  { day: 24, week: 4, category: "distraction", minutes: 0,
    title: "Mañana sin redes",
    lesson: "Un bloque más largo sin el disparador principal confirma que el impulso baja solo, sin pelear contra él.",
    task: "Pasa la mañana (hasta el mediodía) sin abrir redes sociales." },
  { day: 25, week: 4, category: "overwhelm", minutes: 10,
    title: "Cerrar lo abierto",
    lesson: "Las tareas \"a medias\" son las que más energía mental consumen, aunque no las estés mirando.",
    task: "Termina algo que dejaste a medias hace semanas." },
  { day: 26, week: 4, category: "communication", minutes: 3,
    title: "Agradecer",
    lesson: "Cerrar el ciclo social de esta última semana refuerza que el cambio no fue solo individual.",
    task: "Agradece a alguien que te ayudó a avanzar esta semana." },
  { day: 27, week: 4, category: "clutter", minutes: 5,
    title: "Sin que te lo recuerden",
    lesson: "Cuando el hábito ya no necesita el recordatorio de la app, el patrón nuevo quedó instalado.",
    task: "Repite tu ritual de \"dejar listo para mañana\" del día 15, sin que te lo recuerden." },
  { day: 28, week: 4, category: "mindset", minutes: 5, checkin: true,
    title: "Lo que cambió",
    lesson: "Comparar el día 1 con hoy es la mejor evidencia de que esto no fue fuerza de voluntad — fue repetición.",
    task: "Escribe 3 cosas que cambiaron en cómo manejás tus pendientes desde el día 1." },
  { day: 29, week: 4, category: "overwhelm", minutes: 5,
    title: "El día ideal",
    lesson: "Visualizar el patrón que querés sostener ayuda a que siga siendo automático después del día 30.",
    task: "Planea, en 5 minutos, cómo se ve tu día ideal de acá a 30 días más." },
  { day: 30, week: 4, category: "mindset", minutes: 5,
    title: "Celebrar",
    lesson: "Completaste el plan de 30 días. El patrón nuevo ya es tuyo — seguí sosteniéndolo un día a la vez.",
    task: "Elige una forma de premiarte por haber completado el plan." },
];

export const CHECKIN_QUESTION = {
  prompt: "¿Cuánta energía mental le estás dedicando a mantener el orden y las tareas pendientes esta semana?",
  options: [
    { value: 3, label: "Estrés constante de fondo" },
    { value: 2, label: "Lo pienso varias veces al día" },
    { value: 1, label: "De vez en cuando" },
    { value: 0, label: "Casi ni lo pienso" },
  ],
};

export const STRINGS = {
  appName: BRAND,
  tagline: "5 minutos al día para dejar de procrastinar",
  onboarding: {
    welcomeTitle: "Bienvenido/a a StartNow",
    welcomeBody: "Un plan de 30 días, con una sola tarea pequeña por día. Nada de reorganizar tu vida en un fin de semana.",
    withQuizTitle: (name) => `Hola${name ? " " + name : ""}, ya tenemos tu perfil`,
    withQuizBody: "Armamos tu plan de 30 días con lo que nos contaste en el quiz.",
    noQuizTitle: "Contanos qué te cuesta más",
    noQuizBody: "Así priorizamos las tareas de tu plan de 30 días.",
    categoryPrompt: "¿Qué te gustaría trabajar primero?",
    namePrompt: "¿Cómo te llamamos?",
    namePlaceholder: "Tu nombre",
    startBtn: "Empezar mi día 1",
    continueBtn: "Continuar",
  },
  nav: { today: "Hoy", plan: "Plan", progress: "Progreso", settings: "Ajustes" },
  today: {
    dayLabel: (n) => `Día ${n} de 30`,
    streakLabel: "de racha",
    doneTitle: "¡Listo por hoy!",
    doneBody: "Volvé mañana para tu próxima microtarea.",
    markDone: "Marcar como completado",
    alreadyDone: "Completado hoy ✓",
    minutesLabel: (m) => (m === 0 ? "Todo el día" : `${m} min`),
    finishedAllTitle: "Completaste los 30 días 🎉",
    finishedAllBody: "El patrón ya es tuyo. Podés repetir el plan desde el día 1 para reforzarlo, o seguir a tu ritmo.",
    restartBtn: "Repetir el plan",
  },
  plan: {
    title: "Tu plan de 30 días",
    locked: "Se desbloquea cuando llegues a ese día",
    today: "Hoy",
    done: "Completado",
  },
  progress: {
    title: "Tu progreso",
    currentStreak: "Racha actual",
    longestStreak: "Mejor racha",
    totalDays: "Días completados",
    days: "días",
    calendarTitle: "Últimos 30 días",
    checkinsTitle: "Revisiones semanales",
    noCheckins: "Todavía no tenés revisiones semanales — aparecen los días 7, 14, 21 y 28.",
  },
  checkin: {
    title: "Revisión semanal",
    submitBtn: "Guardar",
  },
  settings: {
    title: "Ajustes",
    nameLabel: "Nombre",
    reminderTitle: "Recordatorio diario",
    reminderBody: "Activá las notificaciones del navegador para que te avisemos de tu tarea del día.",
    reminderEnable: "Activar notificaciones",
    reminderOn: "Notificaciones activadas ✓",
    reminderBlocked: "Las notificaciones están bloqueadas en tu navegador. Podés habilitarlas desde la configuración del sitio.",
    resetTitle: "Reiniciar progreso",
    resetBody: "Borra tu racha y tus días completados. No se puede deshacer.",
    resetBtn: "Reiniciar todo",
    resetConfirm: "¿Seguro que querés borrar todo tu progreso?",
    installTitle: "Instalar en tu celular",
    installBody: "Agregá StartNow a tu pantalla de inicio para abrirla como una app.",
  },
};
