export const BRAND = "StartNow";

export const CATEGORY_META = {
  clutter: { icon: "🧹", label: "Tidying up" },
  distraction: { icon: "📵", label: "Distractions" },
  overwhelm: { icon: "🧠", label: "Overwhelm" },
  communication: { icon: "💬", label: "Put-off conversations" },
  mindset: { icon: "🌱", label: "Self-criticism" },
};

// Maps quiz answers to the category highlighted in the welcome message.
export const TRIGGER_TO_CATEGORY = {
  "Stress and anxiety": "overwhelm",
  "Overthinking": "overwhelm",
  "Perfectionism": "mindset",
  "Self-doubt": "mindset",
  "Relationship problems": "communication",
  "Emotional trauma": "mindset",
};
export const AVOIDANCE_TO_CATEGORY = {
  overwhelm: "overwhelm",
  distraction: "distraction",
};

export const WEEKS = [
  { week: 1, title: "2-minute wins", desc: "Tiny tasks that teach your brain to finish things." },
  { week: 2, title: "Breaking the distraction loop", desc: "Take the friction out of the decisions you put off most." },
  { week: 3, title: "Consistency without willpower", desc: "Keep your progress going without having to push harder." },
  { week: 4, title: "Automatic patterns", desc: "The new stuff stops feeling like effort." },
];

export const PLAN = [
  { day: 1, week: 1, category: "clutter", minutes: 2,
    title: "Three things out of place",
    lesson: "This isn't about the objects. It's about training your brain to follow through on tiny commitments without overthinking them.",
    task: "Put away three things you can see right now. That's it." },
  { day: 2, week: 1, category: "distraction", minutes: 3,
    title: "Selective silence",
    lesson: "Every notification reopens a decision your brain had already closed. Fewer interruptions, less fatigue.",
    task: "Mute notifications from just one app for the next 2 hours." },
  { day: 3, week: 1, category: "clutter", minutes: 5,
    title: "Clear it, don't organize it",
    lesson: "Clearing a surface completely, without deciding where everything goes, skips the decision fatigue that freezes you.",
    task: "Pick one flat surface. Clear it off completely. Don't organize it yet — just clear it." },
  { day: 4, week: 1, category: "overwhelm", minutes: 4,
    title: "Name the list",
    lesson: "Naming what you're avoiding, without acting on it yet, turns down the anxiety of having it \"floating around\" in your head.",
    task: "Write down the 3 tasks you avoid the most. Don't do them yet — just name them." },
  { day: 5, week: 1, category: "communication", minutes: 3,
    title: "The text you've been avoiding",
    lesson: "Putting off a conversation makes it bigger in your head than it really is.",
    task: "Send a message you've been putting off for days. It can be as simple as \"Hey, are we still on?\"" },
  { day: 6, week: 1, category: "clutter", minutes: 5,
    title: "Five pieces of clothing",
    lesson: "Small, repeated wins train your brain better than one big, one-off effort.",
    task: "Put away 5 pieces of clothing that are out of place." },
  { day: 7, week: 1, category: "overwhelm", minutes: 5, checkin: true,
    title: "File three things",
    lesson: "End of week one. Check in: are you asking yourself \"where do I even start?\" less often than before?",
    task: "File or delete 3 documents (paper or digital) on your desk that you no longer need." },

  { day: 8, week: 2, category: "distraction", minutes: 5,
    title: "Inbox",
    lesson: "A packed inbox is a list of decisions you haven't made. Shrinking it turns down the background noise.",
    task: "Delete 20 old emails from your inbox." },
  { day: 9, week: 2, category: "mindset", minutes: 8,
    title: "80% counts too",
    lesson: "Perfectionism doesn't help you finish better — it keeps you from finishing. Practicing \"good enough\" is a skill.",
    task: "Pick a task you've been waiting to do \"perfectly\" and take it to 80%. Stop there on purpose." },
  { day: 10, week: 2, category: "distraction", minutes: 2,
    title: "Friction on purpose",
    lesson: "You don't need willpower if you add one extra step to the habit you want to cut back on.",
    task: "Move your favorite social media app to the last screen of your phone." },
  { day: 11, week: 2, category: "overwhelm", minutes: 5,
    title: "Split it in three",
    lesson: "Big tasks create a tangle of competing options. Breaking them down gives you one clear path.",
    task: "Break your biggest pending task into 3 small steps. Write them down." },
  { day: 12, week: 2, category: "clutter", minutes: 4,
    title: "Decide or delete",
    lesson: "Pending decisions take up mental space even when you're not looking at them.",
    task: "Go through a wish list or shopping cart you've left sitting: buy it or delete it." },
  { day: 13, week: 2, category: "communication", minutes: 3,
    title: "Schedule it, don't solve it",
    lesson: "Scheduling a tough conversation is a small commitment that takes away the weight of \"someday.\"",
    task: "Schedule that tough conversation you've been avoiding (don't have it yet — just put it on the calendar)." },
  { day: 14, week: 2, category: "distraction", minutes: 25, checkin: true,
    title: "Protected block",
    lesson: "End of week two. An uninterrupted block trains your brain to sit with the urge to check your phone.",
    task: "Turn on \"Do Not Disturb\" for your next 25-minute work block." },

  { day: 15, week: 3, category: "clutter", minutes: 5,
    title: "Ready for tomorrow",
    lesson: "Starting the day with a clear space cuts down the decisions you have to make before 9 a.m.",
    task: "Before bed, get your desk or kitchen ready for tomorrow." },
  { day: 16, week: 3, category: "overwhelm", minutes: 10,
    title: "Urgent stuff first",
    lesson: "Checking your phone before you start resets the tangle of options that's so hard to sort out.",
    task: "Pick the most urgent task of the day and do it first, before you check your phone." },
  { day: 17, week: 3, category: "mindset", minutes: 3,
    title: "And I kept going anyway",
    lesson: "Being hard on yourself after a mistake doesn't make you more productive — it just wears you out faster.",
    task: "Write down a recent mistake and finish it with: \"and I kept going anyway.\"" },
  { day: 18, week: 3, category: "distraction", minutes: 8,
    title: "Under 15",
    lesson: "Keeping your inbox low is easier than emptying it all at once — that's why it works as a daily habit.",
    task: "Go through your inbox and get it under 15 unarchived emails." },
  { day: 19, week: 3, category: "communication", minutes: 10,
    title: "The scheduled conversation",
    lesson: "You already took the hardest step on day 13. Today you just have to follow through.",
    task: "Have the conversation you scheduled on day 13, or reschedule it for a specific date." },
  { day: 20, week: 3, category: "clutter", minutes: 10,
    title: "The joy test",
    lesson: "Holding each item and asking whether it sparks joy forces you to actually decide instead of putting the decision off again. It's not about owning less — it's about a different relationship with your things.",
    task: "Pick one small category (your socks, your T-shirts, your books). Hold each item and ask yourself: does this spark joy? If not, thank it and donate it or toss it." },
  { day: 21, week: 3, category: "overwhelm", minutes: 5, checkin: true,
    title: "The no-drama task",
    lesson: "End of week three. The goal isn't perfection — it's noticing the shift in how you start things.",
    task: "Look back at your week: which task did you finish without going around in circles? Write it down." },

  { day: 22, week: 4, category: "mindset", minutes: 2,
    title: "Say it out loud",
    lesson: "Naming your own progress strengthens the loop just as much as finishing the task itself.",
    task: "Notice one task you did today without procrastinating. Acknowledge it out loud." },
  { day: 23, week: 4, category: "clutter", minutes: 10,
    title: "That drawer",
    lesson: "You've built the habit — the kind of task that used to eat a whole afternoon now takes minutes.",
    task: "Organize a drawer or digital folder that's been bugging you for a while." },
  { day: 24, week: 4, category: "distraction", minutes: 0,
    title: "A social-free morning",
    lesson: "A longer stretch without your main trigger shows you the urge fades on its own, without fighting it.",
    task: "Spend the morning (until noon) without opening social media." },
  { day: 25, week: 4, category: "overwhelm", minutes: 10,
    title: "Close what's open",
    lesson: "Half-finished tasks drain the most mental energy, even when you're not looking at them.",
    task: "Finish something you left half-done weeks ago." },
  { day: 26, week: 4, category: "communication", minutes: 3,
    title: "Say thanks",
    lesson: "Closing the social loop this last week reinforces that the change wasn't only about you.",
    task: "Thank someone who helped you move forward this week." },
  { day: 27, week: 4, category: "clutter", minutes: 5,
    title: "No reminder needed",
    lesson: "When the habit no longer needs the app's reminder, the new pattern has stuck.",
    task: "Repeat your \"ready for tomorrow\" routine from day 15, without being reminded." },
  { day: 28, week: 4, category: "mindset", minutes: 5, checkin: true,
    title: "What changed",
    lesson: "Comparing day 1 to today is the best proof that this wasn't willpower — it was repetition.",
    task: "Write down 3 things that have changed in how you handle your to-dos since day 1." },
  { day: 29, week: 4, category: "overwhelm", minutes: 5,
    title: "Your ideal day",
    lesson: "Picturing the pattern you want to keep helps it stay automatic after day 30.",
    task: "Take 5 minutes to plan what your ideal day looks like 30 days from now." },
  { day: 30, week: 4, category: "mindset", minutes: 5,
    title: "Celebrate",
    lesson: "You finished the 30-day plan. The new pattern is yours now — keep it going one day at a time.",
    task: "Pick a way to reward yourself for finishing the plan." },
];

export const CHECKIN_QUESTION = {
  prompt: "How much mental energy are you spending on keeping things tidy and on top of your to-dos this week?",
  options: [
    { value: 3, label: "Constant background stress" },
    { value: 2, label: "I think about it several times a day" },
    { value: 1, label: "Every now and then" },
    { value: 0, label: "I barely think about it" },
  ],
};

export const STRINGS = {
  appName: BRAND,
  tagline: "5 minutes a day to stop procrastinating",
  onboarding: {
    welcomeTitle: "Welcome to StartNow",
    welcomeBody: "A 30-day plan with just one small task a day. No reorganizing your whole life in a weekend.",
    withQuizTitle: (name) => `Hi${name ? " " + name : ""}, we've got your profile`,
    withQuizBody: "We set up your 30-day plan based on what you told us in the quiz.",
    noQuizTitle: "Tell us what's hardest for you",
    noQuizBody: "That way we can prioritize the tasks in your 30-day plan.",
    categoryPrompt: "What would you like to work on first?",
    namePrompt: "What should we call you?",
    namePlaceholder: "Your name",
    startBtn: "Start day 1",
    continueBtn: "Continue",
  },
  nav: { today: "Today", plan: "Plan", modules: "Modules", progress: "Progress", settings: "Settings" },
  hello: (name) => `Hi, ${name}`,
  dayShort: (n) => `Day ${n}`,
  weekLabel: (n) => `Week ${n}`,
  closeBtn: "Close",
  today: {
    dayLabel: (n) => `Day ${n} of 30`,
    streakLabel: "day streak",
    featured: "★ Priority for you",
    doneTitle: "Done for today!",
    doneBody: "Come back tomorrow for your next micro-task.",
    markDone: "Mark as done",
    alreadyDone: "Done today ✓",
    minutesLabel: (m) => (m === 0 ? "All day" : `${m} min`),
    finishedAllTitle: "You finished all 30 days 🎉",
    finishedAllBody: "The pattern is yours now. You can repeat the plan from day 1 to lock it in, or keep going at your own pace.",
    restartBtn: "Repeat the plan",
  },
  plan: {
    title: "Your 30-day plan",
    locked: "Unlocks when you reach this day",
    today: "Today",
    done: "Done",
  },
  modules: {
    title: "Bonus modules",
    sub: "Short lessons to add to your 30-day plan, at your own pace.",
    notIncluded: "Not included in your plan. If you bought it, open the activation link you got in Hotmart.",
    activated: "✓ Your extra modules are now unlocked.",
    activatedBtn: "See modules",
    markDone: "Mark as done",
    undo: "✓ Done — undo",
  },
  progress: {
    title: "Your progress",
    currentStreak: "Current streak",
    longestStreak: "Best streak",
    totalDays: "Days completed",
    days: "days",
    calendarTitle: "Last 30 days",
    checkinsTitle: "Weekly check-ins",
    noCheckins: "No weekly check-ins yet — they show up on days 7, 14, 21, and 28.",
  },
  checkin: {
    title: "Weekly check-in",
    submitBtn: "Save",
  },
  settings: {
    title: "Settings",
    nameLabel: "Name",
    reminderTitle: "Daily reminder",
    reminderBody: "Turn on browser notifications so we can remind you about your task for the day.",
    reminderEnable: "Turn on notifications",
    reminderOn: "Notifications on ✓",
    reminderBlocked: "Notifications are blocked in your browser. You can allow them in your site settings.",
    resetTitle: "Reset progress",
    resetBody: "Erases your streak and completed days. This can't be undone.",
    resetBtn: "Reset everything",
    resetConfirm: "Are you sure you want to erase all your progress?",
    installTitle: "Install on your phone",
    installBody: "Add StartNow to your home screen to open it like an app.",
    installBtn: "Install app",
  },
};
