export const BONUS_MODULES_CONTENT = [
  {
    key: "time-focus",
    title: "Mastering time and focus",
    icon: "⏱️",
    description: "5 quick techniques to stop losing focus between tasks.",
    lessons: [
      { n: 1, title: "The 2-minute rule",
        lesson: "If something takes less than 2 minutes, doing it now costs less than writing it down, remembering it, and deciding about it all over again later.",
        task: "Right now, do any to-do that takes less than 2 minutes.", minutes: 5 },
      { n: 2, title: "Single-task blocks",
        lesson: "Every task switch has a hidden cost: your brain takes a while to refocus. One uninterrupted block gets more done than several broken-up ones.",
        task: "Pick a 25-minute block and work on just one task — no extra tabs or apps.", minutes: 25 },
      { n: 3, title: "The list of 3",
        lesson: "When everything is a priority, nothing is. Picking just 3 forces you to actually decide what matters today.",
        task: "Write down the 3 most important things for tomorrow, in order.", minutes: 5 },
      { n: 4, title: "Close before you open",
        lesson: "Leaving tasks half-open is what steals the most focus the next day — not how big the task is.",
        task: "Before you open anything new today, properly close the last thing: save it and jot down where you left off.", minutes: 5 },
      { n: 5, title: "Your peak-energy hour",
        lesson: "Using your best time of day for your most important work pays off more than forcing focus when you're already tired.",
        task: "Figure out your highest-energy hour and block it for tomorrow's most important task.", minutes: 5 },
    ],
  },
  {
    key: "stress-anxiety",
    title: "Managing stress and anxiety",
    icon: "🧘",
    description: "5 quick tools to bring anxiety down in the moment.",
    lessons: [
      { n: 1, title: "4-7-8 breathing",
        lesson: "A longer exhale switches on the part of your nervous system that calms you down — it works in minutes, whether or not the situation changes.",
        task: "Do 4 breathing cycles: breathe in for 4 seconds, hold for 7, breathe out for 8.", minutes: 3 },
      { n: 2, title: "Worry dump",
        lesson: "Writing a worry down moves it out of your head and onto paper — it lightens the mental load even before you solve it.",
        task: "For 3 minutes, write down everything that's worrying you, without editing or fixing anything.", minutes: 3 },
      { n: 3, title: "The realistic \"worst case\"",
        lesson: "Fear is usually bigger and vaguer than the actual problem. Naming the specific worst case makes it manageable.",
        task: "Pick a current worry and write down the realistic worst case — and what you'd do if it happened.", minutes: 5 },
      { n: 4, title: "5-4-3-2-1 grounding",
        lesson: "Naming what your senses pick up interrupts the anxious thought loop and brings you back to the present.",
        task: "Name 5 things you see, 4 you hear, 3 you can touch, 2 you smell, and 1 you taste.", minutes: 3 },
      { n: 5, title: "Worry window",
        lesson: "Pushing worry to a set time (instead of banning it) cuts down how much it spills into the rest of your day.",
        task: "Pick a set 10-minute slot tomorrow to worry on purpose, and jot down today's worries to bring to it.", minutes: 5 },
    ],
  },
  {
    key: "habits",
    title: "Building habits that last",
    icon: "🔁",
    description: "5 principles to help a new habit survive past week two.",
    lessons: [
      { n: 1, title: "Habit stacking",
        lesson: "A new habit sticks better when it piggybacks on one you already do every day, instead of relying on memory alone.",
        task: "Pick a habit you already have and add the new one right after it.", minutes: 5 },
      { n: 2, title: "Make it obvious",
        lesson: "Seeing the cue for a habit (the object, the app, the clothes) does more to get you started than willpower.",
        task: "Leave something in plain sight that reminds you of your new habit (like your workout clothes next to the bed).", minutes: 5 },
      { n: 3, title: "The minimum streak",
        lesson: "The smallest version of a habit, done every day, builds identity faster than a perfect version done once in a while.",
        task: "If you're short on time today, do the 30-second version of your habit — but don't skip it.", minutes: 2 },
      { n: 4, title: "Never miss twice",
        lesson: "Missing one day is an accident. Missing two in a row starts a new pattern — so what matters is how fast you bounce back.",
        task: "If you missed a habit yesterday, do it today, no excuses, even if it's the minimum version.", minutes: 5 },
      { n: 5, title: "Identity check",
        lesson: "Habits last when they connect to who you are, not just to a result you want.",
        task: "Finish this sentence out loud: \"I'm someone who ______,\" using the habit you're building.", minutes: 3 },
    ],
  },
  {
    key: "relationships",
    title: "Managing relationships",
    icon: "💬",
    description: "5 simple gestures to keep your relationships strong without a huge effort.",
    lessons: [
      { n: 1, title: "The 1-minute text",
        lesson: "Reconnecting doesn't take a perfect message — it takes sending one.",
        task: "Send a short message to someone you've lost touch with.", minutes: 2 },
      { n: 2, title: "Listen without planning your reply",
        lesson: "Planning your answer while the other person is talking is the main reason people feel \"unheard.\"",
        task: "In your next conversation, silently count to 2 before you respond.", minutes: 5 },
      { n: 3, title: "The direct ask",
        lesson: "Hints breed resentment when they're missed. Asking directly reduces conflict — it doesn't create it.",
        task: "Ask someone close to you, directly and plainly, for something you need.", minutes: 5 },
      { n: 4, title: "Repair fast",
        lesson: "Relationships that last aren't the ones that avoid conflict — they're the ones that repair quickly after it.",
        task: "If there's unresolved tension with someone, send them a simple message today to open the conversation.", minutes: 5 },
      { n: 5, title: "Specific thanks",
        lesson: "\"Thanks for everything\" gets forgotten. Thanking someone for something specific really strengthens the bond.",
        task: "Thank someone for something specific and recent, in detail.", minutes: 3 },
    ],
  },
  {
    key: "money",
    title: "Managing money",
    icon: "💰",
    description: "5 simple habits to stop avoiding your finances.",
    lessons: [
      { n: 1, title: "The invisible expense",
        lesson: "Subscriptions and small recurring charges fly under the radar until you look at them just once.",
        task: "Go over your spending from the last 2 weeks and flag the charge that surprised you most.", minutes: 8 },
      { n: 2, title: "The 24-hour rule",
        lesson: "Waiting a day on a non-essential purchase cuts impulse buying way down, no willpower needed.",
        task: "If you want to buy something non-essential today, wait 24 hours before deciding.", minutes: 2 },
      { n: 3, title: "The envelope method",
        lesson: "Splitting your money by category (even just in your head) keeps one big expense from eating the rest of the month.",
        task: "Pick 3 spending categories for this month and write down how much you want to put toward each.", minutes: 8 },
      { n: 4, title: "Automate your savings",
        lesson: "Saving first (before you spend) works better than trying to save whatever's left at the end of the month.",
        task: "Set up an automatic transfer to a savings account, even a tiny one.", minutes: 8 },
      { n: 5, title: "A 5-minute weekly review",
        lesson: "Avoiding your money out of anxiety only creates more anxiety. A short, judgment-free check breaks that cycle.",
        task: "Spend 5 minutes looking at your balance and this week's spending, without judging yourself.", minutes: 5 },
    ],
  },
];

export default BONUS_MODULES_CONTENT;
