export const BONUS_MODULES_CONTENT = [
  {
    key: "time-focus",
    title: "Dominio del tiempo y el enfoque",
    icon: "⏱️",
    description: "5 técnicas cortas para dejar de perder el foco entre tareas.",
    lessons: [
      { n: 1, title: "La regla de los 2 minutos",
        lesson: "Si algo toma menos de 2 minutos, hacerlo ahora sale más barato que anotarlo, recordarlo y volver a decidir sobre eso después.",
        task: "Hacé ahora mismo cualquier pendiente que tome menos de 2 minutos.", minutes: 5 },
      { n: 2, title: "Bloques de una sola tarea",
        lesson: "Cada cambio de tarea tiene un costo invisible: tu cerebro tarda en volver a enfocarse. Un bloque sin cambios rinde más que varios bloques interrumpidos.",
        task: "Elegí un bloque de 25 minutos y trabajá en una sola tarea, sin pestañas ni apps extra.", minutes: 25 },
      { n: 3, title: "La lista de 3",
        lesson: "Cuando todo es prioridad, nada lo es. Elegir solo 3 te obliga a decidir de verdad qué importa hoy.",
        task: "Escribí las 3 cosas más importantes de mañana, en orden.", minutes: 5 },
      { n: 4, title: "Cerrar antes de abrir",
        lesson: "Dejar tareas a medias sin cerrarlas es lo que más roba foco al día siguiente — no el tamaño de la tarea en sí.",
        task: "Antes de abrir algo nuevo hoy, cerrá formalmente lo anterior: guardalo y anotá dónde quedaste.", minutes: 5 },
      { n: 5, title: "Tu hora de mayor energía",
        lesson: "Usar tu mejor momento del día para lo más importante rinde más que intentar forzar concentración cuando ya estás cansado/a.",
        task: "Identificá tu hora de más energía y reservá ahí tu tarea más importante de mañana.", minutes: 5 },
    ],
  },
  {
    key: "stress-anxiety",
    title: "Manejo del estrés y la ansiedad",
    icon: "🧘",
    description: "5 herramientas rápidas para bajar la ansiedad en el momento.",
    lessons: [
      { n: 1, title: "Respiración 4-7-8",
        lesson: "Alargar la exhalación activa el sistema nervioso que te calma — funciona en minutos, sin depender de que la situación cambie.",
        task: "Hacé 4 ciclos de respiración: inhalá 4 segundos, sostené 7, exhalá 8.", minutes: 3 },
      { n: 2, title: "Descarga de preocupaciones",
        lesson: "Escribir una preocupación la saca de tu cabeza y la pone en un papel — reduce la carga mental aunque no la resuelvas todavía.",
        task: "Escribí durante 3 minutos todo lo que te preocupa, sin editar ni corregir.", minutes: 3 },
      { n: 3, title: "El \"peor caso\" realista",
        lesson: "El miedo suele ser más grande y más vago que el problema real. Ponerle nombre concreto al peor escenario lo hace manejable.",
        task: "Elegí una preocupación actual y escribí el peor escenario real, y qué harías si pasara.", minutes: 5 },
      { n: 4, title: "Anclaje sensorial (5-4-3-2-1)",
        lesson: "Nombrar lo que percibís con los sentidos interrumpe el bucle de pensamientos ansiosos y te trae de vuelta al presente.",
        task: "Nombrá 5 cosas que ves, 4 que escuchás, 3 que tocás, 2 que olés y 1 que saboreás.", minutes: 3 },
      { n: 5, title: "Ventana de preocupación",
        lesson: "Postergar la preocupación a un horario fijo (en vez de prohibírtela) reduce cuánto invade el resto del día.",
        task: "Elegí un horario fijo de 10 minutos mañana para preocuparte a propósito, y anotá las preocupaciones de hoy para llevarlas ahí.", minutes: 5 },
    ],
  },
  {
    key: "habits",
    title: "Construcción de hábitos duraderos",
    icon: "🔁",
    description: "5 principios para que un hábito nuevo sobreviva más de dos semanas.",
    lessons: [
      { n: 1, title: "Apilar hábitos",
        lesson: "Un hábito nuevo se sostiene mejor si se apoya en uno que ya hacés todos los días, en vez de depender de acordarte solo.",
        task: "Elegí un hábito que ya tenés instalado y sumale el hábito nuevo justo después.", minutes: 5 },
      { n: 2, title: "Hazlo obvio",
        lesson: "Ver la señal del hábito (el objeto, la app, la ropa) influye más que la fuerza de voluntad para empezar.",
        task: "Dejá a la vista algo que te recuerde tu hábito nuevo (por ejemplo, la ropa de entrenar junto a la cama).", minutes: 5 },
      { n: 3, title: "La racha mínima",
        lesson: "La versión mínima de un hábito, hecha todos los días, construye identidad más rápido que una versión perfecta hecha a veces.",
        task: "Si hoy no tenés tiempo, hacé la versión de 30 segundos de tu hábito — pero no la saltees.", minutes: 2 },
      { n: 4, title: "No rompas la cadena dos veces",
        lesson: "Fallar un día es un accidente. Fallar dos seguidos empieza a instalar un patrón nuevo — por eso lo que importa es la velocidad de recuperación.",
        task: "Si ayer fallaste un hábito, hacelo hoy sin excusas, aunque sea en su versión mínima.", minutes: 5 },
      { n: 5, title: "Revisión de identidad",
        lesson: "Los hábitos duran cuando se conectan con quién sos, no solo con un resultado que querés lograr.",
        task: "Completá en voz alta: \"Soy alguien que ______\", con el hábito que estás construyendo.", minutes: 3 },
    ],
  },
  {
    key: "relationships",
    title: "Gestión de las relaciones",
    icon: "💬",
    description: "5 gestos concretos para sostener vínculos sin esfuerzo enorme.",
    lessons: [
      { n: 1, title: "El mensaje de 1 minuto",
        lesson: "Reconectar no necesita un mensaje perfecto — necesita que lo mandes.",
        task: "Enviá un mensaje corto a alguien con quien perdiste contacto.", minutes: 2 },
      { n: 2, title: "Escucha sin preparar la respuesta",
        lesson: "Preparar tu respuesta mientras el otro habla es la principal razón por la que sentimos que \"no nos escuchan\".",
        task: "En tu próxima conversación, contá hasta 2 en silencio antes de responder.", minutes: 5 },
      { n: 3, title: "El pedido directo",
        lesson: "Las indirectas generan resentimiento cuando no se entienden. Pedir directamente reduce el conflicto, no lo aumenta.",
        task: "Pedile directamente a alguien cercano algo que necesitás, sin rodeos.", minutes: 5 },
      { n: 4, title: "Reparar rápido",
        lesson: "Las relaciones que duran no son las que evitan el conflicto — son las que reparan rápido después de uno.",
        task: "Si tenés una tensión pendiente con alguien, mandale hoy un mensaje simple para abrir la conversación.", minutes: 5 },
      { n: 5, title: "Agradecimiento específico",
        lesson: "\"Gracias por todo\" se olvida. Agradecer algo puntual y concreto fortalece el vínculo de verdad.",
        task: "Agradecele a alguien por algo específico y reciente, con detalle.", minutes: 3 },
    ],
  },
  {
    key: "money",
    title: "Manejo del dinero",
    icon: "💰",
    description: "5 hábitos simples para dejar de evitar tus finanzas.",
    lessons: [
      { n: 1, title: "El gasto invisible",
        lesson: "Las suscripciones y gastos chicos recurrentes pasan desapercibidos hasta que los revisás una sola vez.",
        task: "Revisá tus gastos de las últimas 2 semanas y marcá el que más te sorprendió.", minutes: 8 },
      { n: 2, title: "Regla de las 24 horas",
        lesson: "Postergar una compra no esencial un día reduce muchísimo la compra impulsiva, sin necesitar fuerza de voluntad.",
        task: "Si querés comprar algo no esencial hoy, esperá 24 horas antes de decidir.", minutes: 2 },
      { n: 3, title: "El sobre de categorías",
        lesson: "Separar el dinero por categoría (aunque sea mentalmente) evita que un gasto grande se coma el resto del mes.",
        task: "Elegí 3 categorías de gasto de este mes y anotá cuánto querés destinar a cada una.", minutes: 8 },
      { n: 4, title: "Automatiza el ahorro",
        lesson: "Ahorrar primero (antes de gastar) funciona mejor que intentar ahorrar lo que sobra al final del mes.",
        task: "Programá una transferencia automática, aunque sea mínima, a una cuenta de ahorro.", minutes: 8 },
      { n: 5, title: "Revisión semanal de 5 minutos",
        lesson: "Evitar mirar la plata por ansiedad genera más ansiedad. Una revisión corta y sin juzgarte corta ese ciclo.",
        task: "Mirá tu saldo y tus gastos de la semana durante 5 minutos, sin juzgarte.", minutes: 5 },
    ],
  },
];

export default BONUS_MODULES_CONTENT;
