// Interactive bonus workbooks (EN). Same structure and ids as workbooksContent.es.js.
const WORKBOOKS = [
  {
    key: "reto-7",
    number: 1,
    badge: "🎁 SPECIAL BONUS #1",
    title: "StartNow: 7-Day Challenge",
    tagline: "The 2-minute protocol to stop waiting for “the perfect moment” and get moving again.",
    valueLabel: "Perceived value:",
    valueAmount: "$17–$27 USD",
    img: "/shared/images/bonos/bono1-en.jpg",
    icon: "⚡",
    intro: [
      "Over the next 7 days you won't try to become a perfectly productive person.",
      "You'll practice something far more important: starting again.",
      "Each day you'll get one simple action you can finish in a few minutes, to lower the resistance of getting started and bring back the feeling of progress.",
    ],
    days: [
      {
        n: 1, title: "Break the inertia", icon: "🎯",
        objective: "Prove to yourself that you can start without waiting to feel like it.",
        blocks: [
          { t: "h", text: "Today's mission" },
          { t: "p", text: "Think of just one thing you've been avoiding. Not five. Not a list of twenty. Just one." },
          { t: "field", id: "d1-cosa", label: "What I've been avoiding:", rows: 2 },
          { t: "p", text: "Now ask yourself: “What is the smallest possible version of this task?”" },
          { t: "list", items: [
            "Tidy the room → pick up 3 objects.",
            "Answer emails → open the inbox.",
            "Exercise → put on your shoes.",
            "Study → open the book.",
            "Work on a project → open the document.",
          ] },
          { t: "field", id: "d1-pequena", label: "My smallest version:", rows: 2 },
          { t: "challenge", title: "⏱️ The 2-minute rule", text: "Set a 2-minute timer. Do only that first step. When time is up, you're allowed to stop." },
          { t: "timer", seconds: 120 },
          { t: "check", id: "d1-hecho", label: "I did my 2 minutes" },
          { t: "h", text: "🧠 Reflection" },
          { t: "field", id: "d1-antes", label: "Before I started, I thought that…", rows: 2 },
          { t: "field", id: "d1-despues", label: "After I started, I discovered that…", rows: 2 },
        ],
        win: "You didn't need to finish. You needed to prove you could start.",
      },
      {
        n: 2, title: "Make it ridiculously small", icon: "🔬",
        objective: "Learn to spot when you're turning a small task into a mountain.",
        blocks: [
          { t: "p", text: "Today, pick one pending task and write it down." },
          { t: "field", id: "d2-tengo", label: "I have to…", rows: 2 },
          { t: "p", text: "Now ask yourself: “What is the first physical movement I would have to make?”" },
          { t: "list", items: [
            "❌ “I have to organize my house.” → ✅ “I'm going to put one glass in the kitchen.”",
            "❌ “I have to start my project.” → ✅ “I'm going to open the document.”",
            "❌ “I have to exercise.” → ✅ “I'm going to put on my shoes.”",
          ] },
          { t: "field", id: "d2-movimiento", label: "My first physical movement:", rows: 2 },
          { t: "challenge", title: "⚡ Your mission", text: "Do only that movement. If you want to keep going, keep going. If not, you can stop." },
          { t: "check", id: "d2-hecho", label: "I made my movement" },
          { t: "check", id: "d2-siguio", label: "And I kept going a bit longer (optional)" },
        ],
        win: "“Small doesn't mean insignificant. Small means possible.”",
      },
      {
        n: 3, title: "Remove the decision", icon: "🧩",
        objective: "Stop negotiating with yourself every time you need to start.",
        blocks: [
          { t: "p", text: "One of the most draining things is this mental conversation: “Should I do it now?” “Maybe later.” “Let me finish this first.” “I don't feel like it.” “After I check my phone.” Today you'll end that negotiation." },
          { t: "h", text: "Create your rule" },
          { t: "p", text: "Complete: When __________ happens, I will __________ for 2 minutes." },
          { t: "list", items: [
            "When I finish my coffee → I'll tidy 3 things.",
            "When I open my computer → I'll work 2 minutes on my project.",
            "When I get home → I'll put away 3 objects.",
          ] },
          { t: "field", id: "d3-senal", label: "When… (my cue)", rows: 2 },
          { t: "field", id: "d3-accion", label: "I will… (for 2 minutes)", rows: 2 },
          { t: "challenge", title: "⚡ Your mission", text: "Pick a cue that happens naturally today. When it happens: don't think. Execute." },
          { t: "check", id: "d3-hecho", label: "The cue happened and I acted without negotiating" },
        ],
        win: "You don't need to decide every time. You can prepare the decision in advance.",
      },
      {
        n: 4, title: "Face what you've been avoiding", icon: "🧗",
        objective: "Get closer to an uncomfortable task without having to solve all of it.",
        blocks: [
          { t: "p", text: "There's probably a task you've been avoiding because it triggers an uncomfortable emotion: fear of getting it wrong, boredom, frustration, uncertainty, not knowing where to start, or feeling it will be too much." },
          { t: "field", id: "d4-evito", label: "I'm avoiding…", rows: 2 },
          { t: "field", id: "d4-siento", label: "…because it makes me feel…", rows: 2 },
          { t: "p", text: "Now drop the whole task and ask yourself: “What can I do for just 2 minutes?”" },
          { t: "field", id: "d4-dosmin", label: "My 2 minutes will be:", rows: 2 },
          { t: "timer", seconds: 120 },
          { t: "check", id: "d4-hecho", label: "I got closer to the task for 2 minutes" },
          { t: "quote", text: "You don't need to solve the whole problem today. You only need to show your brain: “I can approach this without having to solve it all.”" },
        ],
        win: "Today you didn't beat the task. You beat the distance between you and the task.",
      },
      {
        n: 5, title: "Create your “START button”", icon: "🔘",
        objective: "Create a repeatable starting signal, not a perfect routine.",
        blocks: [
          { t: "p", text: "Today you'll create a small ritual your brain can associate with starting. It should take less than 60 seconds." },
          { t: "list", items: [
            "Put your phone face down.",
            "Take one deep breath.",
            "Open the document.",
            "Turn on a lamp.",
            "Put on headphones.",
            "Make water or coffee.",
            "Write down the first action.",
          ] },
          { t: "h", text: "My START ritual (3 steps max)" },
          { t: "field", id: "d5-p1", label: "1.", rows: 1 },
          { t: "field", id: "d5-p2", label: "2.", rows: 1 },
          { t: "field", id: "d5-p3", label: "3.", rows: 1 },
          { t: "challenge", title: "⚡ Your mission", text: "Do your ritual. Then: 2 minutes of action." },
          { t: "timer", seconds: 120 },
          { t: "check", id: "d5-ritual", label: "I did my ritual" },
          { t: "check", id: "d5-accion", label: "I did my 2 minutes of action" },
        ],
        win: "The goal isn't a perfect routine. It's a repeatable signal to start.",
      },
      {
        n: 6, title: "Swap “I have to” for “I'm going to”", icon: "💬",
        objective: "Change the language you use with yourself so starting feels possible.",
        blocks: [
          { t: "p", text: "Compare: “I have to clean the whole house.” with “I'm going to put away three things.” Or “I have to finish the report.” with “I'm going to open the document and write one sentence.”" },
          { t: "h", text: "Your mission: three sentences" },
          { t: "p", text: "Write three sentences that usually start with “I have to…” and turn them into “I'm going to…”" },
          { t: "field", id: "d6-t1", label: "I have to… (1)", rows: 1 },
          { t: "field", id: "d6-v1", label: "I'm going to… (1)", rows: 1 },
          { t: "field", id: "d6-t2", label: "I have to… (2)", rows: 1 },
          { t: "field", id: "d6-v2", label: "I'm going to… (2)", rows: 1 },
          { t: "field", id: "d6-t3", label: "I have to… (3)", rows: 1 },
          { t: "field", id: "d6-v3", label: "I'm going to… (3)", rows: 1 },
          { t: "challenge", title: "⚡ Now", text: "Do only the first step of one of your three sentences." },
          { t: "check", id: "d6-hecho", label: "I did the first step" },
        ],
        win: "“When you change the size of the action, the feeling of starting changes.”",
      },
      {
        n: 7, title: "Your new way to start", icon: "🏁",
        objective: "Create your own StartNow Protocol with what you've learned.",
        blocks: [
          { t: "p", text: "You made it to the last day. But this isn't the end. Think about what you learned these 7 days and complete:" },
          { t: "h", text: "🧠 My StartNow Protocol" },
          { t: "field", id: "d7-siento", label: "1. When I'm avoiding something, I usually feel:", rows: 2 },
          { t: "field", id: "d7-senal", label: "2. The cue I'll use to start is:", rows: 2 },
          { t: "field", id: "d7-paso", label: "3. My ridiculously small first step will be:", rows: 2 },
          { t: "field", id: "d7-ritual", label: "4. My starting ritual will be:", rows: 2 },
          { t: "p", text: "5. I'll work for:" },
          { t: "check", id: "d7-t2", label: "2 minutes" },
          { t: "check", id: "d7-t5", label: "5 minutes" },
          { t: "check", id: "d7-t10", label: "10 minutes" },
          { t: "quote", text: "6. My starting phrase: “I don't need to finish. I just need to start.”" },
          { t: "h", text: "🏆 Your final challenge" },
          { t: "p", text: "Pick a task you've been avoiding for several days. Don't finish it. Don't try to make up for lost time." },
          { t: "list", items: [
            "1️⃣ Make it small.",
            "2️⃣ Set up your cue.",
            "3️⃣ Do your ritual.",
            "4️⃣ Set a timer.",
            "5️⃣ Start for 2 minutes.",
          ] },
          { t: "timer", seconds: 120 },
          { t: "check", id: "d7-final", label: "I completed my final challenge" },
          { t: "field", id: "d7-cambio", label: "What just changed?", rows: 3 },
        ],
        win: "You didn't need to finish it all. You needed to prove to yourself that you can start.",
      },
    ],
    closing: {
      title: "Congratulations. You just did something important.",
      paragraphs: [
        "Maybe in these 7 days you didn't clean your whole house. Maybe you didn't finish all your projects. Maybe you still have things pending. And that's okay.",
        "Because this challenge was never about finishing everything. It was about proving something to yourself: that you can start even when you don't feel like it.",
        "The next time that “I'll do it later…” feeling shows up, remember: make it smaller, do it for 2 minutes, and start. Don't wait to feel ready.",
      ],
      signature: "StartNow.",
    },
    bridge: "Now that you know how to start, let's remove one of the main places you run to when something feels hard: your phone.",
  },
  {
    key: "anti-scroll",
    number: 2,
    badge: "🎁 SPECIAL BONUS #2",
    title: "The Anti-Scroll Protocol",
    tagline: "7 days to reclaim your attention and stop escaping to your phone when you have something important to do.",
    valueLabel: "Value:",
    valueAmount: "$19 USD",
    img: "/shared/images/bonos/bono2-en.jpg",
    icon: "📵",
    intro: [
      "You don't need to give up your phone. You need to stop using it as an escape every time something feels uncomfortable.",
      "In just 7 days you'll learn to notice when you're using your phone to avoid a task, and to apply small actions to get back to what you really wanted to do, without deleting your social media or living without a phone.",
    ],
    features: [
      "Escape-moment detector",
      "The 10-second rule",
      "The 2-minute technique",
      "No-scroll zone",
      "Attention exercises",
      "Personal anti-scroll protocol",
      "7-day final challenge",
    ],
    days: [
      {
        n: 1, title: "Discover your escape", icon: "🔍",
        objective: "Find out when and why you reach for your phone.",
        blocks: [
          { t: "p", text: "Today you don't have to delete any app. Just observe. Every time you pick up your phone without planning to, ask yourself: “What was I doing right before I picked it up?” And write it down." },
          { t: "quote", text: "Example: I was writing a report → felt bored → opened Instagram." },
          { t: "h", text: "📝 Your log" },
          { t: "h", text: "Escape #1" },
          { t: "field", id: "d1-a1", label: "What was I doing?", rows: 1 },
          { t: "field", id: "d1-b1", label: "What was I feeling?", rows: 1 },
          { t: "field", id: "d1-c1", label: "What did I do on my phone?", rows: 1 },
          { t: "h", text: "Escape #2" },
          { t: "field", id: "d1-a2", label: "What was I doing?", rows: 1 },
          { t: "field", id: "d1-b2", label: "What was I feeling?", rows: 1 },
          { t: "field", id: "d1-c2", label: "What did I do on my phone?", rows: 1 },
          { t: "h", text: "Escape #3" },
          { t: "field", id: "d1-a3", label: "What was I doing?", rows: 1 },
          { t: "field", id: "d1-b3", label: "What was I feeling?", rows: 1 },
          { t: "field", id: "d1-c3", label: "What did I do on my phone?", rows: 1 },
        ],
        win: "💡 Often the problem doesn't start when you unlock your phone. It starts a few seconds earlier.",
      },
      {
        n: 2, title: "The 10-second rule", icon: "⏳",
        objective: "Create a small space between the urge and the action.",
        blocks: [
          { t: "p", text: "Today you'll add a small pause. When you feel the urge to check your phone: DON'T FORBID YOURSELF FROM USING IT. Just wait 10 seconds and ask yourself:" },
          { t: "quote", text: "“Do I need it, or am I escaping?”" },
          { t: "p", text: "If you really need it, use it. If you realize you're escaping, go back to the task and do it for 2 minutes." },
          { t: "timer", seconds: 10 },
          { t: "field", id: "d2-veces", label: "How many times did I wait the 10 seconds today?", rows: 1 },
          { t: "field", id: "d2-escape", label: "How many of those times was I escaping?", rows: 1 },
          { t: "check", id: "d2-hecho", label: "I used the 10-second pause at least once" },
        ],
        win: "🧠 We're not trying to remove the urge. We're creating a space between URGE → ACTION. And that space gives you back a choice.",
      },
      {
        n: 3, title: "Phone out of reach", icon: "🚪",
        objective: "Prove you can create 10 minutes of intentional attention.",
        blocks: [
          { t: "p", text: "When you need to focus, don't keep your phone next to you. Put it in another room, in a drawer, in a bag, or at least out of immediate reach." },
          { t: "challenge", title: "⏱️ Your mission", text: "Set a 10-minute timer. During those 10 minutes: one task only. Nothing else. When it ends you can check your phone." },
          { t: "field", id: "d3-tarea", label: "My single task will be:", rows: 1 },
          { t: "field", id: "d3-donde", label: "I left my phone in:", rows: 1 },
          { t: "timer", seconds: 600 },
          { t: "check", id: "d3-hecho", label: "I spent 10 minutes on a single task" },
          { t: "field", id: "d3-nota", label: "What did I notice?", rows: 2 },
        ],
        win: "The goal isn't to spend 8 hours without your phone. It's to create 10 minutes of intentional attention.",
      },
      {
        n: 4, title: "Change the reflex", icon: "🔄",
        objective: "Replace an automatic response.",
        blocks: [
          { t: "p", text: "Normally: uncomfortable task → phone. Today: uncomfortable task → small first step. Every time you notice you want to escape to your phone, do this:" },
          { t: "list", items: [
            "STEP 1 — Put the phone down.",
            "STEP 2 — Ask yourself: “What is the 2-minute version of what I'm avoiding?”",
            "STEP 3 — Do it.",
          ] },
          { t: "quote", text: "Example: “I don't want to work on the report.” → “I'm only going to write the first paragraph.”" },
          { t: "field", id: "d4-evito", label: "What I wanted to avoid today:", rows: 2 },
          { t: "field", id: "d4-version", label: "My 2-minute version:", rows: 2 },
          { t: "timer", seconds: 120 },
          { t: "check", id: "d4-hecho", label: "I changed the reflex at least once" },
        ],
        win: "Every time you choose the first step over the scroll, that path gets easier.",
      },
      {
        n: 5, title: "Create your no-scroll zone", icon: "🛡️",
        objective: "Create a space where your phone doesn't come in for a short period.",
        blocks: [
          { t: "p", text: "Pick a place: 🖥️ your desk, 🛏️ your bedroom, 🍽️ the dining table or 📚 your study spot. For 15 minutes, that space will be a NO-SCROLL ZONE. You don't have to do it all day. Just 15 minutes." },
          { t: "field", id: "d5-zona", label: "My no-scroll zone will be:", rows: 1 },
          { t: "field", id: "d5-tarea", label: "My task for these 15 minutes:", rows: 1 },
          { t: "p", text: "Put your phone far away. Pick a task. And start." },
          { t: "timer", seconds: 900 },
          { t: "h", text: "🏆 If you finish the 15 minutes, check:" },
          { t: "check", id: "d5-c1", label: "I did it even though I didn't feel like it" },
          { t: "check", id: "d5-c2", label: "I didn't need to feel motivated" },
          { t: "check", id: "d5-c3", label: "I was able to concentrate" },
        ],
        win: "Fifteen minutes of real attention are worth more than a half-distracted hour.",
      },
      {
        n: 6, title: "Reclaim your attention", icon: "🔕",
        objective: "Remove unnecessary interruptions and measure who decides your attention.",
        blocks: [
          { t: "p", text: "Today you'll run a small experiment. For one hour, turn off the notifications you don't need. You don't have to delete apps or leave social media. Just remove the unnecessary interruptions. Then observe:" },
          { t: "field", id: "d6-ganas", label: "How many times did I feel like checking my phone?", rows: 1 },
          { t: "field", id: "d6-necesito", label: "How many times did I really need it?", rows: 1 },
          { t: "field", id: "d6-auto", label: "How many times did I check it automatically?", rows: 1 },
          { t: "check", id: "d6-hecho", label: "I did my hour without unnecessary notifications" },
          { t: "quote", text: "“How much of my attention was I deciding, and how much was my phone deciding?”" },
          { t: "field", id: "d6-reflex", label: "My answer:", rows: 3 },
        ],
        win: "Reclaiming your attention starts with deciding what deserves to interrupt you.",
      },
      {
        n: 7, title: "Create your Anti-Scroll Protocol", icon: "🏁",
        objective: "Build your own personal protocol.",
        blocks: [
          { t: "h", text: "🚨 When I feel the urge to escape to my phone:" },
          { t: "list", items: [
            "1. I STOP. I don't unlock it right away.",
            "2. I ASK MYSELF: “Am I looking for something or avoiding something?”",
            "3. IF I'M AVOIDING: I turn the task into a 2-minute action.",
            "4. I MOVE THE PHONE AWAY. Out of reach.",
            "5. I START. I don't need to finish. Just start.",
          ] },
          { t: "h", text: "🧠 My personal protocol" },
          { t: "field", id: "d7-momento", label: "My main escape moment is:", rows: 2 },
          { t: "field", id: "d7-siento", label: "I usually escape to my phone when I feel:", rows: 2 },
          { t: "field", id: "d7-tarea", label: "The task I most often avoid is:", rows: 2 },
          { t: "field", id: "d7-paso", label: "My first 2-minute step will be:", rows: 2 },
          { t: "field", id: "d7-donde", label: "Where I'll leave my phone:", rows: 2 },
          { t: "quote", text: "My emergency phrase: “Am I looking for something… or avoiding something?”" },
          { t: "h", text: "🏆 The final challenge" },
          { t: "p", text: "Tomorrow, when that urge shows up: don't fight it. Observe it. Ask yourself the question. If you're avoiding: put the phone down → make the task ridiculously small → start for 2 minutes. That's it." },
          { t: "check", id: "d7-final", label: "I'll apply my protocol tomorrow" },
        ],
        win: "The goal isn't to use your phone less. It's to stop using it to escape your life.",
      },
    ],
    closing: {
      title: "You don't need to hate your phone",
      paragraphs: [
        "Your phone isn't the enemy. The problem appears when it automatically becomes: boredom → phone, anxiety → phone, hard task → phone, discomfort → phone, “I don't know where to start” → phone.",
        "From now on you have another option: discomfort → pause → small action → START.",
        "You don't need to control every minute of your day. You don't need to delete Instagram. You don't need to live without YouTube. You don't need to become a productivity machine. You only need to get back the ability to choose what you do with your next few minutes.",
        "The goal isn't to use your phone less. It's to stop using it to escape your life.",
      ],
      signature: "StartNow.",
    },
  },
];

export default WORKBOOKS;

export const WORKBOOK_STRINGS = {
  navLabel: "Bonuses",
  free: "FREE",
  title: "Your 2 special bonuses",
  sub: "Two interactive workbooks included with your StartNow. Write, check things off and move at your own pace: your answers are saved on this device.",
  system: "Bonus #1 teaches you how to start. Bonus #2 teaches you not to escape right when you're about to start. They're parts of one system.",
  open: "Open bonus",
  included: "Includes:",
  introTitle: "Before you start",
  dayLabel: (n) => `Day ${n}`,
  objective: "🎯 Goal",
  win: "✅ Win of the day",
  backToIndex: "← Back to index",
  back: "← My bonuses",
  prev: "← Previous day",
  next: "Next day →",
  finish: "See final page",
  intro: "Introduction",
  finalPage: "Final page",
  dayProgress: (a, b) => `${a}/${b} days`,
  markDayDone: "Mark this day as completed",
  dayDone: "✓ Day completed — undo",
  placeholder: "Write here…",
  timerStart: "Start timer",
  timerPause: "Pause",
  timerReset: "Reset",
  timerDone: "Time's up! You can stop.",
  print: "Print or save as PDF",
  nextBonus: "Next bonus →",
};
