// Bonos interactivos (workbooks). Bloques: h, p, list, quote, challenge, field, check, timer.
// Cada field/check necesita un id único dentro de su bono (se guarda en localStorage).
const WORKBOOKS = [
  {
    key: "reto-7",
    number: 1,
    badge: "🎁 BONO ESPECIAL #1",
    title: "StartNow: Reto de 7 días",
    tagline: "El protocolo de 2 minutos para dejar de esperar “el momento perfecto” y volver a ponerte en movimiento.",
    valueLabel: "Valor percibido:",
    valueAmount: "$17–$27 USD",
    img: "/shared/images/bonos/bono1.jpg",
    icon: "⚡",
    intro: [
      "Durante los próximos 7 días no vas a intentar convertirte en una persona perfectamente productiva.",
      "Vas a practicar algo mucho más importante: volver a empezar.",
      "Cada día tendrás una acción sencilla que puedes completar en pocos minutos para reducir la resistencia de comenzar y recuperar la sensación de avance.",
    ],
    days: [
      {
        n: 1, title: "Rompe la inercia", icon: "🎯",
        objective: "Demostrarte que puedes empezar sin esperar a tener ganas.",
        blocks: [
          { t: "h", text: "La misión de hoy" },
          { t: "p", text: "Piensa en una sola cosa que llevas evitando. No elijas cinco. No hagas una lista de veinte. Solo una." },
          { t: "field", id: "d1-cosa", label: "Lo que llevo evitando:", rows: 2 },
          { t: "p", text: "Ahora pregúntate: “¿Cuál sería la versión más pequeña posible de esta tarea?”" },
          { t: "list", items: [
            "Ordenar la habitación → recoger 3 objetos.",
            "Responder correos → abrir el correo.",
            "Hacer ejercicio → ponerte los zapatos.",
            "Estudiar → abrir el libro.",
            "Trabajar en un proyecto → abrir el documento.",
          ] },
          { t: "field", id: "d1-pequena", label: "Mi versión más pequeña:", rows: 2 },
          { t: "challenge", title: "⏱️ Regla de los 2 minutos", text: "Pon un temporizador de 2 minutos. Haz solamente ese primer paso. Cuando termine el tiempo, puedes parar." },
          { t: "timer", seconds: 120 },
          { t: "check", id: "d1-hecho", label: "Hice mis 2 minutos" },
          { t: "h", text: "🧠 Reflexión" },
          { t: "field", id: "d1-antes", label: "Antes de empezar pensaba que…", rows: 2 },
          { t: "field", id: "d1-despues", label: "Después de empezar descubrí que…", rows: 2 },
        ],
        win: "No necesitabas terminar. Necesitabas demostrarte que podías empezar.",
      },
      {
        n: 2, title: "Hazlo ridículamente pequeño", icon: "🔬",
        objective: "Aprender a detectar cuándo estás convirtiendo una tarea pequeña en una montaña.",
        blocks: [
          { t: "p", text: "Hoy elige una tarea pendiente y escríbela." },
          { t: "field", id: "d2-tengo", label: "Tengo que…", rows: 2 },
          { t: "p", text: "Ahora pregúntate: “¿Cuál es el primer movimiento físico que tendría que hacer?”" },
          { t: "list", items: [
            "❌ “Tengo que organizar mi casa.” → ✅ “Voy a poner un vaso en la cocina.”",
            "❌ “Tengo que empezar mi proyecto.” → ✅ “Voy a abrir el documento.”",
            "❌ “Tengo que hacer ejercicio.” → ✅ “Voy a ponerme los zapatos.”",
          ] },
          { t: "field", id: "d2-movimiento", label: "Mi primer movimiento físico:", rows: 2 },
          { t: "challenge", title: "⚡ Tu misión", text: "Haz solamente ese movimiento. Si quieres continuar, continúa. Si no, puedes parar." },
          { t: "check", id: "d2-hecho", label: "Hice mi movimiento" },
          { t: "check", id: "d2-siguio", label: "Y seguí un rato más (opcional)" },
        ],
        win: "“Pequeño no significa insignificante. Pequeño significa posible.”",
      },
      {
        n: 3, title: "Elimina la decisión", icon: "🧩",
        objective: "Dejar de negociar contigo mismo cada vez que tienes que empezar.",
        blocks: [
          { t: "p", text: "Una de las cosas que más desgasta es esta conversación mental: “¿Lo hago ahora?” “Mejor después.” “Primero termino esto.” “No tengo ganas.” “Después de revisar el celular.” Hoy vas a eliminar esa negociación." },
          { t: "h", text: "Crea tu regla" },
          { t: "p", text: "Completa: Cuando __________ ocurra, voy a __________ durante 2 minutos." },
          { t: "list", items: [
            "Cuando termine mi café → voy a ordenar 3 cosas.",
            "Cuando abra el computador → voy a trabajar 2 minutos en mi proyecto.",
            "Cuando llegue a casa → voy a guardar 3 objetos.",
          ] },
          { t: "field", id: "d3-senal", label: "Cuando… (mi señal)", rows: 2 },
          { t: "field", id: "d3-accion", label: "Voy a… (durante 2 minutos)", rows: 2 },
          { t: "challenge", title: "⚡ Tu misión", text: "Elige una señal que ocurra naturalmente hoy. Cuando ocurra: no pienses. Ejecuta." },
          { t: "check", id: "d3-hecho", label: "La señal ocurrió y ejecuté sin negociar" },
        ],
        win: "No necesitas decidir cada vez. Puedes preparar la decisión por adelantado.",
      },
      {
        n: 4, title: "Enfrenta eso que llevas evitando", icon: "🧗",
        objective: "Acercarte a una tarea incómoda sin tener que resolverla toda.",
        blocks: [
          { t: "p", text: "Hay una tarea que probablemente llevas evitando porque te produce una emoción incómoda: miedo a equivocarte, aburrimiento, frustración, incertidumbre, no saber por dónde empezar, o sentir que será demasiado." },
          { t: "field", id: "d4-evito", label: "Estoy evitando…", rows: 2 },
          { t: "field", id: "d4-siento", label: "…porque me hace sentir…", rows: 2 },
          { t: "p", text: "Ahora elimina la tarea completa y pregúntate: “¿Qué puedo hacer durante solamente 2 minutos?”" },
          { t: "field", id: "d4-dosmin", label: "Mis 2 minutos serán:", rows: 2 },
          { t: "timer", seconds: 120 },
          { t: "check", id: "d4-hecho", label: "Me acerqué a la tarea durante 2 minutos" },
          { t: "quote", text: "No necesitas solucionar hoy el problema completo. Solo necesitas demostrarle a tu cerebro: “Puedo acercarme a esto sin tener que resolverlo todo.”" },
        ],
        win: "Hoy no venciste la tarea. Venciste la distancia entre tú y la tarea.",
      },
      {
        n: 5, title: "Crea tu “botón de START”", icon: "🔘",
        objective: "Crear una señal repetible de inicio, no una rutina perfecta.",
        blocks: [
          { t: "p", text: "Hoy vas a crear un pequeño ritual que tu cerebro pueda asociar con comenzar. Debe durar menos de 60 segundos." },
          { t: "list", items: [
            "Poner el celular boca abajo.",
            "Respirar profundamente una vez.",
            "Abrir el documento.",
            "Encender una lámpara.",
            "Ponerte audífonos.",
            "Preparar agua o café.",
            "Escribir la primera acción.",
          ] },
          { t: "h", text: "Mi ritual START (3 pasos máximo)" },
          { t: "field", id: "d5-p1", label: "1.", rows: 1 },
          { t: "field", id: "d5-p2", label: "2.", rows: 1 },
          { t: "field", id: "d5-p3", label: "3.", rows: 1 },
          { t: "challenge", title: "⚡ Tu misión", text: "Haz tu ritual. Después: 2 minutos de acción." },
          { t: "timer", seconds: 120 },
          { t: "check", id: "d5-ritual", label: "Hice mi ritual" },
          { t: "check", id: "d5-accion", label: "Hice mis 2 minutos de acción" },
        ],
        win: "No es crear una rutina perfecta. Es crear una señal repetible de inicio.",
      },
      {
        n: 6, title: "Cambia “tengo que” por “voy a”", icon: "💬",
        objective: "Cambiar el lenguaje con el que te hablas para que empezar se sienta posible.",
        blocks: [
          { t: "p", text: "Compara: “Tengo que limpiar toda la casa.” con “Voy a guardar tres cosas.” O “Tengo que terminar el informe.” con “Voy a abrir el documento y escribir una frase.”" },
          { t: "h", text: "Tu misión: tres frases" },
          { t: "p", text: "Escribe tres frases que normalmente comienzan con “Tengo que…” y conviértelas en “Voy a…”" },
          { t: "field", id: "d6-t1", label: "Tengo que… (1)", rows: 1 },
          { t: "field", id: "d6-v1", label: "Voy a… (1)", rows: 1 },
          { t: "field", id: "d6-t2", label: "Tengo que… (2)", rows: 1 },
          { t: "field", id: "d6-v2", label: "Voy a… (2)", rows: 1 },
          { t: "field", id: "d6-t3", label: "Tengo que… (3)", rows: 1 },
          { t: "field", id: "d6-v3", label: "Voy a… (3)", rows: 1 },
          { t: "challenge", title: "⚡ Ahora", text: "Haz solamente el primer paso de una de tus tres frases." },
          { t: "check", id: "d6-hecho", label: "Hice el primer paso" },
        ],
        win: "“Cuando cambias el tamaño de la acción, cambia la sensación de empezar.”",
      },
      {
        n: 7, title: "Tu nueva forma de empezar", icon: "🏁",
        objective: "Crear tu propio Protocolo StartNow con lo que aprendiste.",
        blocks: [
          { t: "p", text: "Llegaste al último día. Pero este no es el final. Piensa en lo que aprendiste durante estos 7 días y completa:" },
          { t: "h", text: "🧠 Mi Protocolo StartNow" },
          { t: "field", id: "d7-siento", label: "1. Cuando estoy evitando algo, normalmente siento:", rows: 2 },
          { t: "field", id: "d7-senal", label: "2. La señal que voy a utilizar para empezar es:", rows: 2 },
          { t: "field", id: "d7-paso", label: "3. Mi primer paso ridículamente pequeño será:", rows: 2 },
          { t: "field", id: "d7-ritual", label: "4. Mi ritual de inicio será:", rows: 2 },
          { t: "p", text: "5. Voy a trabajar durante:" },
          { t: "check", id: "d7-t2", label: "2 minutos" },
          { t: "check", id: "d7-t5", label: "5 minutos" },
          { t: "check", id: "d7-t10", label: "10 minutos" },
          { t: "quote", text: "6. Mi frase de inicio: “No necesito terminar. Solo necesito empezar.”" },
          { t: "h", text: "🏆 Tu reto final" },
          { t: "p", text: "Elige una tarea que hayas estado evitando durante varios días. No la termines. No intentes recuperar todo el tiempo perdido." },
          { t: "list", items: [
            "1️⃣ Hazla pequeña.",
            "2️⃣ Prepara tu señal.",
            "3️⃣ Haz tu ritual.",
            "4️⃣ Pon un temporizador.",
            "5️⃣ Empieza durante 2 minutos.",
          ] },
          { t: "timer", seconds: 120 },
          { t: "check", id: "d7-final", label: "Completé mi reto final" },
          { t: "field", id: "d7-cambio", label: "¿Qué acaba de cambiar?", rows: 3 },
        ],
        win: "No necesitabas terminarlo todo. Necesitabas demostrarte que puedes empezar.",
      },
    ],
    closing: {
      title: "Felicidades. Acabas de hacer algo importante.",
      paragraphs: [
        "Quizás durante estos 7 días no limpiaste toda tu casa. Quizás no terminaste todos tus proyectos. Quizás todavía tienes cosas pendientes. Y está bien.",
        "Porque este reto nunca se trató de terminarlo todo. Se trató de demostrarte algo: que puedes empezar incluso cuando no tienes ganas.",
        "La próxima vez que aparezca esa sensación de “lo hago después…”, recuerda: hazlo más pequeño, hazlo durante 2 minutos y empieza. No esperes a sentirte preparado.",
      ],
      signature: "StartNow.",
    },
    bridge: "Ahora que sabes cómo empezar, vamos a eliminar uno de los principales lugares a los que huyes cuando algo se siente difícil: tu celular.",
  },
  {
    key: "anti-scroll",
    number: 2,
    badge: "🎁 BONO ESPECIAL #2",
    title: "El Protocolo Anti-Scroll",
    tagline: "7 días para recuperar tu atención y dejar de escapar al celular cuando tienes algo importante que hacer.",
    valueLabel: "Valor:",
    valueAmount: "$19 USD",
    img: "/shared/images/bonos/bono2.jpg",
    icon: "📵",
    intro: [
      "No necesitas dejar tu celular. Necesitas dejar de usarlo como escape cada vez que algo te incomoda.",
      "En solo 7 días vas a aprender a reconocer cuándo estás usando el celular para evitar una tarea y a aplicar pequeñas acciones para volver a lo que realmente querías hacer, sin eliminar tus redes sociales ni vivir sin teléfono.",
    ],
    features: [
      "Detector de momentos de escape",
      "Regla de los 10 segundos",
      "Técnica de los 2 minutos",
      "Zona sin scroll",
      "Ejercicios de atención",
      "Protocolo personal anti-scroll",
      "Reto final de 7 días",
    ],
    days: [
      {
        n: 1, title: "Descubre tu escape", icon: "🔍",
        objective: "Descubrir cuándo y por qué recurres al celular.",
        blocks: [
          { t: "p", text: "Hoy no tienes que eliminar ninguna aplicación. Solo observa. Cada vez que agarres el celular sin haberlo planeado, pregúntate: “¿Qué estaba haciendo justo antes de tomarlo?” Y anótalo." },
          { t: "quote", text: "Ejemplo: Estaba escribiendo un informe → sentí aburrimiento → abrí Instagram." },
          { t: "h", text: "📝 Tu registro" },
          { t: "h", text: "Escape #1" },
          { t: "field", id: "d1-a1", label: "¿Qué estaba haciendo?", rows: 1 },
          { t: "field", id: "d1-b1", label: "¿Qué sentía?", rows: 1 },
          { t: "field", id: "d1-c1", label: "¿Qué hice en el celular?", rows: 1 },
          { t: "h", text: "Escape #2" },
          { t: "field", id: "d1-a2", label: "¿Qué estaba haciendo?", rows: 1 },
          { t: "field", id: "d1-b2", label: "¿Qué sentía?", rows: 1 },
          { t: "field", id: "d1-c2", label: "¿Qué hice en el celular?", rows: 1 },
          { t: "h", text: "Escape #3" },
          { t: "field", id: "d1-a3", label: "¿Qué estaba haciendo?", rows: 1 },
          { t: "field", id: "d1-b3", label: "¿Qué sentía?", rows: 1 },
          { t: "field", id: "d1-c3", label: "¿Qué hice en el celular?", rows: 1 },
        ],
        win: "💡 Muchas veces el problema no comienza cuando desbloqueas el celular. Comienza unos segundos antes.",
      },
      {
        n: 2, title: "La regla de los 10 segundos", icon: "⏳",
        objective: "Crear un pequeño espacio entre el impulso y la acción.",
        blocks: [
          { t: "p", text: "Hoy vas a introducir una pequeña pausa. Cuando sientas el impulso de mirar el celular: NO TE PROHÍBAS USARLO. Simplemente espera 10 segundos y pregúntate:" },
          { t: "quote", text: "“¿Lo necesito o estoy escapando?”" },
          { t: "p", text: "Si realmente lo necesitas, úsalo. Si descubres que estás escapando, vuelve a la tarea y hazla durante 2 minutos." },
          { t: "timer", seconds: 10 },
          { t: "field", id: "d2-veces", label: "¿Cuántas veces esperé los 10 segundos hoy?", rows: 1 },
          { t: "field", id: "d2-escape", label: "¿Cuántas de esas veces estaba escapando?", rows: 1 },
          { t: "check", id: "d2-hecho", label: "Usé la pausa de 10 segundos al menos una vez" },
        ],
        win: "🧠 No estamos intentando eliminar el impulso. Estamos creando un espacio entre IMPULSO → ACCIÓN. Y ese espacio te devuelve una elección.",
      },
      {
        n: 3, title: "Celular fuera de alcance", icon: "🚪",
        objective: "Demostrar que puedes crear 10 minutos de atención intencional.",
        blocks: [
          { t: "p", text: "Cuando necesites concentrarte, no pongas el celular al lado. Ponlo en otra habitación, dentro de un cajón, en una mochila, o al menos fuera de tu alcance inmediato." },
          { t: "challenge", title: "⏱️ Tu misión", text: "Pon un temporizador de 10 minutos. Durante esos 10 minutos: una sola tarea. Nada más. Cuando termine puedes revisar tu teléfono." },
          { t: "field", id: "d3-tarea", label: "Mi tarea única será:", rows: 1 },
          { t: "field", id: "d3-donde", label: "Dejé mi celular en:", rows: 1 },
          { t: "timer", seconds: 600 },
          { t: "check", id: "d3-hecho", label: "Pasé 10 minutos con una sola tarea" },
          { t: "field", id: "d3-nota", label: "¿Qué noté?", rows: 2 },
        ],
        win: "El objetivo no es pasar 8 horas sin celular. Es crear 10 minutos de atención intencional.",
      },
      {
        n: 4, title: "Cambia el reflejo", icon: "🔄",
        objective: "Sustituir una respuesta automática.",
        blocks: [
          { t: "p", text: "Normalmente: tarea incómoda → celular. Hoy: tarea incómoda → primer paso pequeño. Cada vez que notes que quieres escapar al celular, haz esto:" },
          { t: "list", items: [
            "PASO 1 — Deja el celular.",
            "PASO 2 — Pregúntate: “¿Cuál es la versión de 2 minutos de lo que estoy evitando?”",
            "PASO 3 — Hazla.",
          ] },
          { t: "quote", text: "Ejemplo: “No quiero trabajar en el informe.” → “Voy a escribir solamente el primer párrafo.”" },
          { t: "field", id: "d4-evito", label: "Lo que quise evitar hoy:", rows: 2 },
          { t: "field", id: "d4-version", label: "Mi versión de 2 minutos:", rows: 2 },
          { t: "timer", seconds: 120 },
          { t: "check", id: "d4-hecho", label: "Cambié el reflejo al menos una vez" },
        ],
        win: "Cada vez que eliges el primer paso en vez del scroll, ese camino se hace más fácil.",
      },
      {
        n: 5, title: "Crea tu zona sin scroll", icon: "🛡️",
        objective: "Crear un espacio donde el celular no entra durante un periodo corto.",
        blocks: [
          { t: "p", text: "Elige un lugar: 🖥️ tu escritorio, 🛏️ tu habitación, 🍽️ la mesa del comedor o 📚 tu lugar de estudio. Durante 15 minutos, ese espacio será ZONA SIN SCROLL. No tienes que hacerlo todo el día. Solo 15 minutos." },
          { t: "field", id: "d5-zona", label: "Mi zona sin scroll será:", rows: 1 },
          { t: "field", id: "d5-tarea", label: "Mi tarea de estos 15 minutos:", rows: 1 },
          { t: "p", text: "Pon el celular lejos. Elige una tarea. Y empieza." },
          { t: "timer", seconds: 900 },
          { t: "h", text: "🏆 Si terminas los 15 minutos, marca:" },
          { t: "check", id: "d5-c1", label: "Lo hice aunque no tenía ganas" },
          { t: "check", id: "d5-c2", label: "No necesité sentirme motivado" },
          { t: "check", id: "d5-c3", label: "Pude concentrarme" },
        ],
        win: "Quince minutos de atención real valen más que una hora a medias.",
      },
      {
        n: 6, title: "Recupera tu atención", icon: "🔕",
        objective: "Eliminar las interrupciones innecesarias y medir quién decide tu atención.",
        blocks: [
          { t: "p", text: "Hoy vas a hacer un pequeño experimento. Durante una hora, desactiva las notificaciones que no sean necesarias. No necesitas borrar aplicaciones ni abandonar redes. Simplemente elimina las interrupciones innecesarias. Después observa:" },
          { t: "field", id: "d6-ganas", label: "¿Cuántas veces sentí ganas de mirar el celular?", rows: 1 },
          { t: "field", id: "d6-necesito", label: "¿Cuántas veces realmente lo necesitaba?", rows: 1 },
          { t: "field", id: "d6-auto", label: "¿Cuántas veces lo miré automáticamente?", rows: 1 },
          { t: "check", id: "d6-hecho", label: "Hice mi hora sin notificaciones innecesarias" },
          { t: "quote", text: "“¿Cuánto de mi atención estaba decidiendo yo y cuánto estaba decidiendo mi teléfono?”" },
          { t: "field", id: "d6-reflex", label: "Mi respuesta:", rows: 3 },
        ],
        win: "Recuperar tu atención empieza por decidir qué merece interrumpirte.",
      },
      {
        n: 7, title: "Crea tu Protocolo Anti-Scroll", icon: "🏁",
        objective: "Construir tu propio protocolo personal.",
        blocks: [
          { t: "h", text: "🚨 Cuando sienta que quiero escapar al celular:" },
          { t: "list", items: [
            "1. ME DETENGO. No desbloqueo inmediatamente.",
            "2. ME PREGUNTO: “¿Estoy buscando algo o estoy evitando algo?”",
            "3. SI ESTOY EVITANDO: convierto la tarea en una acción de 2 minutos.",
            "4. ALEJO EL CELULAR. Lo pongo fuera de alcance.",
            "5. EMPIEZO. No necesito terminar. Solo empezar.",
          ] },
          { t: "h", text: "🧠 Mi protocolo personal" },
          { t: "field", id: "d7-momento", label: "Mi principal momento de escape es:", rows: 2 },
          { t: "field", id: "d7-siento", label: "Normalmente escapo al celular cuando siento:", rows: 2 },
          { t: "field", id: "d7-tarea", label: "La tarea que más suelo evitar es:", rows: 2 },
          { t: "field", id: "d7-paso", label: "Mi primer paso de 2 minutos será:", rows: 2 },
          { t: "field", id: "d7-donde", label: "Dónde voy a dejar mi celular:", rows: 2 },
          { t: "quote", text: "Mi frase de emergencia: “¿Estoy buscando algo… o estoy evitando algo?”" },
          { t: "h", text: "🏆 El reto final" },
          { t: "p", text: "Mañana, cuando aparezca ese impulso: no luches contra él. Obsérvalo. Hazte la pregunta. Si estás evitando: deja el celular → haz la tarea ridículamente pequeña → empieza durante 2 minutos. Eso es todo." },
          { t: "check", id: "d7-final", label: "Voy a aplicar mi protocolo mañana" },
        ],
        win: "El objetivo no es usar menos el celular. Es dejar de usarlo para escapar de tu vida.",
      },
    ],
    closing: {
      title: "No necesitas odiar tu celular",
      paragraphs: [
        "Tu teléfono no es el enemigo. El problema aparece cuando se convierte automáticamente en: aburrimiento → celular, ansiedad → celular, tarea difícil → celular, incomodidad → celular, “no sé por dónde empezar” → celular.",
        "A partir de ahora tienes otra opción: incomodidad → pausa → acción pequeña → START.",
        "No necesitas controlar cada minuto de tu día. No necesitas eliminar Instagram. No necesitas vivir sin YouTube. No necesitas convertirte en una máquina de productividad. Solo necesitas recuperar la capacidad de elegir qué haces con tus próximos minutos.",
        "El objetivo no es usar menos el celular. Es dejar de usarlo para escapar de tu vida.",
      ],
      signature: "StartNow.",
    },
  },
];

export default WORKBOOKS;

export const WORKBOOK_STRINGS = {
  navLabel: "Bonos",
  free: "GRATIS",
  title: "Tus 2 bonos especiales",
  sub: "Dos workbooks interactivos incluidos con tu StartNow. Escribe, marca y avanza a tu ritmo: tus respuestas se guardan en este dispositivo.",
  system: "Bono #1 te enseña a empezar. Bono #2 te enseña a no escapar justo cuando vas a empezar. Son partes de un mismo sistema.",
  open: "Abrir bono",
  included: "Incluye:",
  introTitle: "Antes de empezar",
  dayLabel: (n) => `Día ${n}`,
  objective: "🎯 Objetivo",
  win: "✅ Victoria del día",
  backToIndex: "← Volver al índice",
  back: "← Mis bonos",
  prev: "← Día anterior",
  next: "Día siguiente →",
  finish: "Ver página final",
  intro: "Introducción",
  finalPage: "Página final",
  dayProgress: (a, b) => `${a}/${b} días`,
  markDayDone: "Marcar este día como completado",
  dayDone: "✓ Día completado — desmarcar",
  placeholder: "Escribe aquí…",
  timerStart: "Iniciar temporizador",
  timerPause: "Pausar",
  timerReset: "Reiniciar",
  timerDone: "¡Tiempo! Puedes parar.",
  print: "Imprimir o guardar en PDF",
  nextBonus: "Siguiente bono →",
};
